version: 2.1
orbs:
  localstack: localstack/platform@1.0.1
jobs:
  localstack-test:
    executor: localstack/default
    environment:
      AWS_DEFAULT_REGION: us-east-1
      AWS_SECRET_ACCESS_KEY: foo
      AWS_ACCESS_KEY_ID: bar
    steps:
      - localstack/startup
      - checkout
      - install_serverless
#      - install_terraform
      - run:
          name: python test
          command: |
            python3 main.py
            python3 main-test.py
      - run:
          name: Run Serverless
          command: |
            serverless create --template aws-nodejs --path localstack-lambda
            serverless deploy --stage local
            serverless info --stage local
            serverless invoke local -f hello -l
      - run:
          name: aws stuff
          command: |
            awslocal --version
            awslocal s3 mb s3://local-bucket
            awslocal s3 ls
#     - run:
#          name: terraform
#          command: |
#            terraform init -input=false
#            terraform apply -auto-approve -input=false
#      - run:
#          name: lambda
#          command: |
#            awslocal lambda list-functions
#            awslocal lambda invoke --function-name ExampleLambda /dev/stdout
#          # *invoking* the lambda requires configuring LocalStack with LAMBDA_EXECUTOR=docker ,
#          # which runs docker-in-docker and doesn't work trivially in Circle.
#
commands:
  install_terraform:
    description: "install terraform"
    steps:
      - run:
          name: Install Terraform
          environment:
            TF_VERSION: 1.0.11
          command: |
            mkdir -p ~/bin
            cd ~/bin
            wget https://releases.hashicorp.com/terraform/${TF_VERSION}/terraform_${TF_VERSION}_linux_amd64.zip
            unzip terraform_${TF_VERSION}_linux_amd64.zip
            echo 'export PATH=~/bin:$PATH'  >> $BASH_ENV
            terraform --version
  install_serverless:
    description: "install serverless"
    steps:
      - run:
          name: Install Serverless
          command: |
            sudo apt update
            sudo apt install nodejs npm
            sudo npm install -g serverless
            node --version  
            serverless --version
workflows:
  localstack-test:
    jobs:
      - localstack-test
