version: 2.1
orbs:
  localstack: localstack/platform@1.0.1
jobs:
  localstack-test:
    executor: localstack/default
    steps:
      - localstack/startup
      - checkout
      - run:
          python3 main.py
          python3 main-test.py
          command: |
            awslocal s3 mb s3://test-bucket
            awslocal s3 ls
workflows:
  localstack-test:
    jobs:
      - localstack-test
